### ISSUE TITLE
download full-size twitter images

### ISSUE THREAD

**Issue by clavinet** [Antosik/images-grabber#16]
Images on twitter can be downloaded in full resolution by appending ":orig" to the URL at the end, looking like this

https://pbs.twimg.com/media/abcde.jpg:orig

it would be nice if images-grabber would do this by default or have an option for it.

**Comment by Antosik** [comment]
Hello!

Resolved in ef9590a and published in v3.1.3
Update `images-grabber` to new version c:

Thanks for your issue c:
